server:
  servlet:
    context-path: /msdemo
  port: 8080

spring:
  datasource:
    druid:
      url:  jdbc:mysql://localhost:3306/msdemo
      driver-class-name:  com.mysql.cj.jdbc.Driver
      #com.mysql.cj.jdbc.Driver com.mysql.jdbc.Driver
      username:  root
      password:  123456
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM DUAL
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,wall
  # 配置单个上传文件最大为10
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 100MB
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

## mybatis 配置
mybatis:
  type-aliases-package: com.gallop.managersys.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
## 通用 Mapper 配置
mapper:
  mappers: com.gallop.utils.MyMapper
  not-empty: false
  identity: MYSQL

msdemo:
    #对象存储配置
  storage:
      # 当前工作的对象存储模式，分别是local、aliyun、tencent
      active: fastdfs
      # 本地对象存储配置信息
      local:
        storagePath: d:\\temp\\storage
        # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
        address: http://192.168.2.122:8080/msdemo/admin/storage/fetch/
      fastdfs:
        baseUrl: http://192.168.2.125:8888/
fdfs:
  # 读取时间
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
    width: 80
    height: 80
  #TrackerList参数,支持多个
  tracker-list:
    - 192.168.2.125:22122

